version: '3.8'

services:
  backend:
    build:
      context: ./backend-rust
      dockerfile: Dockerfile
    container_name: backend-rust
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:3000"
    depends_on:
      - backend