version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-rust
    ports:
      - "8000:8000"
    volumes:
      - ./backend/cosmic_cat_cafe.db:/app/cosmic_cat_cafe.db
      - ./backend/Rocket.toml:/app/Rocket.toml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend