version: '3.8'
# Used to deploy without building images
services:
  backend:
    image: etxsae/catcafe-backend
    container_name: backend-rust
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      ARG  REACT_APP_BACKEND_URL
      
    container_name: frontend 
    ports:
      - "80:3000"
    depends_on:
      - backend