FROM rust:latest AS builder

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y libsqlite3-dev
RUN cargo build --release

# Imagen final
FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y ca-certificates sqlite3
WORKDIR /app

COPY --from=builder /app/target/release/backend-rust /usr/local/bin/app
COPY cosmic_cat_cafe.db /app/cosmic_cat_cafe.db


# Exponemos el puerto 8000
EXPOSE 8000

CMD ["app"]
