FROM rust:latest AS builder

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y libsqlite3-dev
RUN cargo build --release

# Etapa final: bookworm-slim (glibc >= 2.34)
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates sqlite3
WORKDIR /app

COPY --from=builder /app/target/release/backend-rust /usr/local/bin/app
COPY cosmic_cat_cafe.db /app/cosmic_cat_cafe.db
COPY Rocket.toml /app/Rocket.toml

EXPOSE 8000
CMD ["app"]
